import fs from "node:fs";
import path from "node:path";

type Status = "verified-local" | "not-started";
type Requirement = {
  id: string;
  source: string;
  section: string;
  requirement: string;
  status: Status;
};

const root = process.cwd();
const configPath = path.join(root, "config", "developer-control-plane-requirements.json");
const generatedPath = path.join(
  root,
  ".generated",
  "requirements",
  "developer-control-plane-requirements.json",
);
const ledgerPath = path.join(root, "DEVELOPER_CONTROL_PLANE_LEDGER.md");

export function validate(requirements: Requirement[]) {
  const ids = new Set<string>();
  for (const item of requirements) {
    if (!/^DCP-REQ-\d{3}$/.test(item.id)) throw new Error(`Invalid DCP requirement id: ${item.id}`);
    if (ids.has(item.id)) throw new Error(`Duplicate DCP requirement id: ${item.id}`);
    ids.add(item.id);
    if (!item.source || path.isAbsolute(item.source) || item.source.includes(".."))
      throw new Error(`Unsafe DCP source path: ${item.source}`);
    if (!item.section || !item.requirement)
      throw new Error(`Incomplete DCP requirement: ${item.id}`);
    if (item.status !== "verified-local" && item.status !== "not-started")
      throw new Error(`Invalid DCP status: ${item.id}`);
  }
}

function table(rows: string[][]) {
  const widths = rows[0].map((_, column) => Math.max(...rows.map((row) => row[column].length), 3));
  const line = (row: string[]) =>
    `| ${row.map((cell, column) => cell.padEnd(widths[column])).join(" | ")} |`;
  const separator = line(widths.map((width) => "-".repeat(width)));
  return [line(rows[0]), separator, ...rows.slice(1).map(line)].join("\n");
}

export function renderLedger(requirements: Requirement[]) {
  const rows = [
    ["ID", "Source", "Section", "Status", "Requirement"],
    ...requirements.map((item) => [
      item.id,
      item.source,
      item.section,
      item.status,
      item.requirement,
    ]),
  ];
  return `# Developer Control Plane ledger

> Generated by \`pnpm control-plane:requirements:check\` from \`config/developer-control-plane-requirements.json\`. This isolated ledger documents DCP-0 only; it must not change RC3/T999 or root release classifications.

${table(rows)}
`;
}

function main() {
  const parsed = JSON.parse(fs.readFileSync(configPath, "utf8")) as {
    requirements?: Requirement[];
  };
  if (!Array.isArray(parsed.requirements)) throw new Error("DCP requirements are missing");
  validate(parsed.requirements);
  fs.mkdirSync(path.dirname(generatedPath), { recursive: true });
  const output = {
    schemaVersion: 1,
    generatedBy: "pnpm control-plane:requirements:check",
    requirements: parsed.requirements,
  };
  fs.writeFileSync(generatedPath, `${JSON.stringify(output, null, 2)}\n`);
  fs.writeFileSync(ledgerPath, renderLedger(parsed.requirements));
  console.log(`Generated ${parsed.requirements.length} isolated DCP requirement records.`);
}

if (!process.env.VITEST) main();
